ALTER TABLE fila_user
ADD COLUMN check_in BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE fila_user
ADD COLUMN notificado BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE fila_user 
ADD COLUMN status VARCHAR(255) NOT NULL DEFAULT 'Na fila';